replicaCount: 1
image:
  repository: levyam/qr-code-backend
  pullPolicy: IfNotPresent
  tag: deploy-ba361f3713538714c53f2c3ac2d1ef4ecf143e7b
service:
  port: 3001
  targetPort: 3000
  name: https
  protocol: TCP
ingress:
  domain: thasfincommunity.com.br
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - paths:
        - path: /
clusterIssuer:
  enabled: true
  acme:
    email: community.thasfin@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
