replicaCount: 1
image:
  repository: levyam/qr-code-backend
  pullPolicy: IfNotPresent
  tag: deploy-7be2bb9d3298c4010aa8113d67ceb4c643d63b45
service:
  port: 3001
  targetPort: 3000
  name: https
  protocol: TCP
ingress:
  domain: thasfincommunity.com.br
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - paths:
        - path: /
clusterIssuer:
  enabled: true
  acme:
    email: community.thasfin@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
