replicaCount: 1
image:
  repository: levyam/qr-code-backend
  pullPolicy: IfNotPresent
  tag: main-d745535b74f24dd45385f308c2bfb5d9c569a76e
service:
  port: 3001
  targetPort: 3000
  name: https
  protocol: TCP
ingress:
  domain: thasfincommunity.com.br
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - paths:
        - path: /
clusterIssuer:
  enabled: true
  acme:
    email: community.thasfin@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
